### ISSUE TITLE
[configuration] Theme switch / Admin tools madness or conflict

### ISSUE THREAD

**Issue by plegall** [mistic100/Piwigo#329]
**Reported by montuno on 7 Jul 2015 20:56**

**Version:** 2.7.4

Hi,
Here is a strange issue,

When I activate admin tools plugin while running SimpleNG theme, I observe that I cannot switch to another theme afterward - meaning whatever the theme I choose the front gallery remains stuck on SimpleNG theme.

On the top of that - lets say the said &#039;active&#039; theme is &#039;dark&#039; in the UI and the admin tools plugin is still activated (remind, the front gallery still stuck on SimpleNG). Now if I deactivate SimpleNG theme nothing more happen (still stuck of simpleNG), however if I DELETE simpleNG theme I got the error:

Warning: include(/themeconf.inc.php): failed to open stream: No such file or directory in /srv/www/piwigo/include/template.class.php on line 1156

Warning: include(): Failed opening &#039;/themeconf.inc.php&#039; for inclusion (include_path=&#039;.:/usr/share/php:/usr/share/pear&#039;) in /srv/www/piwigo/include/template.class.php on line 1156

Fatal error: Uncaught exception &#039;SmartyException&#039; with message &#039;Unable to load template file &#039;menubar.tpl&#039;&#039; in /srv/www/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php:127 Stack trace: #0 /srv/www/piwigo/include/template.class.php(484): Smarty_Internal_TemplateBase-&gt;fetch(&#039;menubar.tpl&#039;) #1 /srv/www/piwigo/include/template.class.php(407): Template-&gt;parse(&#039;menubar&#039;, true) #2 /srv/www/piwigo/include/block.class.php(205): Template-&gt;assign_var_from_handle(&#039;MENUBAR&#039;, &#039;menubar&#039;) #3 /srv/www/piwigo/include/menubar.inc.php(337): BlockManager-&gt;apply(&#039;MENUBAR&#039;, &#039;menubar.tpl&#039;) #4 /srv/www/piwigo/include/menubar.inc.php(30): initialize_menu() #5 /srv/www/piwigo/index.php(120): include(&#039;/srv/www/piwigo...&#039;) #6 {main} thrown in /srv/www/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 127

IF now, I try to deactivate admin tools : bingo the active theme in the UI (eg : &#039;dark&#039;) comes effective.

Could you help me to understand what is the problem here ?

[Piwigo Bugtracker #3230](http://piwigo.org/bugs/view.php?id=3230)

**Comment by nnifty** [comment]
I have the same issue using Piwigo 2.7.4 and Admin Tools plugin 2.7.3.
After some code digging (I'm new to Piwigo, now I migrate from G3) I realized, that this behavior applies to "Multi View" feature of this plugin.
Under admin account you can change used theme "on the fly" using "Theme" droplist in "Tools" menu (top right corner) and this settings stored in current session.
So this behavior is not a bug, it's feature, which can be useful for developers.

So in your case - even if you change active theme in administrative interface, you won't see any changes, because current session still keep settings with first used in this session theme.
You can change theme using "Tools" menu in top right corner, or for example you can close your internet browser (all windows) which will close current session, then open it again - and see actual active theme.
And of course all this things applies to Admin account only, i.e. you can just logout from admin account and voila - see the current active theme.

P.S. Sorry for my english :)

**Comment by eliz82** [comment]
I just got identical errors with Piwigo 2.8.6

Warning: include(/themeconf.inc.php): failed to open stream: No such file or directory in /.../piwigo/include/template.class.php on line 1156

Warning: include(): Failed opening '/themeconf.inc.php' for inclusion (include_path='.:') in /.../piwigo/include/template.class.php on line 1156

Fatal error: Uncaught --> Smarty: Unable to load template file 'menubar.tpl' <-- thrown in /.../piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139
----------
I tried to activate theme bootstrap darkroom. I didnt make the theme default. Then in admin toolbar i tried to chose the theme bootstrap darkroom and got this error. 

I enter administration I delete the theme bootstrap darkroom but nothing change. 
The error disappears only if i disable the Admin Tools plugin.

**Comment by mogsama** [comment]
I also got the warning in front end:
`Warning: include(/themeconf.inc.php): failed to open stream: No such file or directory in /.../piwigo/include/template.class.php on line 1156`

I did a compare with another good site with same config and found the reason is I delete the default folder in /themes/

**Comment by samwilson** [comment]
I was getting the `include(/themeconf.inc.php): failed to open stream` error as well, with Bootstrap Darkroom theme when I first added it in a `themes/darkroom` directory, enabled it, and then renamed the directory to `bootstrap_darkroom`. (Don't know if this helps, but it struck me that there should be some neater fallback for non-existing themes...)

**Comment by pj-claeys** [comment]
I ran into the same problem. The issue is that there is no event when the themes are actived/deactived/deleted so AdminTools doesn't know about it and shows stale data to the admin user. 

This can be solved by triggering an event on theme status changes, catching them in AdminTools and invalidating the cache.

**Comment by plegall** [comment]
Hi @pj-claeys 

OK for your pull-request, before I merge it, I would like to know if it's enough to fix the issue or if Admin Tools also needs some changes?

**Comment by pj-claeys** [comment]
Hi @plegall, Admin Tools needs a change as well, but it needs the new event to be able to act on.

I have mentioned it in the related ticket there: https://github.com/Piwigo/AdminTools/issues/8
